# Generated by Django 4.1.7 on 2023-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strawberry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
