# Generated by Django 4.1.7 on 2023-05-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strawberry_app', '0005_rename_name_months_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='name',
            new_name='culture',
        ),
    ]
