# Generated by Django 4.1.7 on 2023-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strawberry_app', '0009_mediafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantimage',
            name='file',
        ),
        migrations.AddField(
            model_name='plantimage',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='profile_pics/'),
        ),
    ]
